name: Excavator

on:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'
  workflow_dispatch:

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
      - name: Update readme
        shell: pwsh
        run: ./bin/update_readme.ps1
